### ISSUE TITLE
Matrix dimension mismatch

### ISSUE THREAD

**Issue by Jeep1991** [lakehanne/Savitzky-Golay#1]
Hi ! I dowloaded your implementation of SG filter and did not succeed to run it as is. The assertion comes at the line `MatrixXf G = Sd * Rinv * RinvT;` in the function `sgdiff`. With `F=5` and `k=3`, it seems that the dimensions of `Sd` is 5x4 but the dimensions of `Rinv` and `RinvT` is 1x1. Hence, the multiplication `Sd * Rinv * RinvT` cause the program to abord. I did not edited anything, just downloaded the library, created a blank project in VS 2015, imported those plus the Eigen library. Any idea ?

**Comment by robotsorcerer** [comment]
Hi @Jeep1991 , sorry about the late response. For some reason, I did not get a notification from github about this issue. I was skimming through this repo this evening when I noticed the opened issue; hence my late response. 

I did not test the code in Windows, sorry. It was developed in Ubuntu 14.04. I just compiled it again on ubuntu and it indeed does generate the `Vandermonde` matrix:

The size of `Sd` is `[5 x 2]` actually because we extract the rank deficient matrix from the vandermonde (or projection matrix) that we earlier calculated; For F = 5 and k = 3, `R` and `Rinv` are both square `[2 x 2]` matrices; So `[5 x 2] x [2 x 2] x [2 x 2]` gives matrix `G` which is the matrix of differentiators, defined as `G = S x (S' x S)^(-1)`  in eqn 8.3.90 in the book. See this portion of the [code](https://github.com/lakehanne/Savitzky-Golay/blob/master/savgol.cpp#L68-#L71) for greater clarification.

I made certain changes to the source code this evening that allows you to change the values of `F`, `k` and the time-series data at run-time. Please go thorugh the README all over again. 

If you have the time, you could send a PR that reads an input stream of data from a text file and filters the read data.

Thanks for your comments and please let me know if you have further questions.
